# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/megazdb
spring.datasource.username=postgres
spring.datasource.password=1379
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA) - Configurações do ORM
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configurações adicionais
spring.jpa.show-sql=true
